version: "3"

services:

  chr-7-2-3:
    image: chr_7_2_3
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - "12222:22"
      - "12223:23"
      - "18728:8728"
      - "18729:8729"
      - "8001:80"
      - "2000:2000"
      - "8291:8291"
